'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { memo } from 'react';
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Target, Users, CheckCircle, BarChart3 } from 'lucide-react';
const CustomTooltip = memo(({ active, payload, label }) => {
    if (active && payload && payload.length) {
        return (_jsxs("div", { className: "bg-slate-900 p-3 rounded-lg shadow-xl border border-slate-700", children: [_jsx("p", { className: "text-white font-semibold mb-1", children: label }), payload.map((entry, index) => (_jsxs("p", { className: "text-sm", style: { color: entry.color }, children: [entry.name, ": ", typeof entry.value === 'number' && entry.value > 1000
                            ? `$${(entry.value / 1000).toFixed(0)}K`
                            : entry.value] }, index)))] }));
    }
    return null;
});
CustomTooltip.displayName = 'CustomTooltip';
const RevenueChart = memo(({ data }) => (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl p-6 rounded-xl border border-slate-700/50", children: [_jsxs("h3", { className: "text-lg font-semibold text-white mb-4 flex items-center gap-2", children: [_jsx(BarChart3, { size: 20, className: "text-blue-400" }), "Revenue & Growth Trends"] }), _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(AreaChart, { data: data, children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "colorMrr", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#10B981", stopOpacity: 0.8 }), _jsx("stop", { offset: "95%", stopColor: "#10B981", stopOpacity: 0.1 })] }), _jsxs("linearGradient", { id: "colorPipeline", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#3B82F6", stopOpacity: 0.8 }), _jsx("stop", { offset: "95%", stopColor: "#3B82F6", stopOpacity: 0.1 })] })] }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#334155" }), _jsx(XAxis, { dataKey: "month", stroke: "#94a3b8" }), _jsx(YAxis, { stroke: "#94a3b8", tickFormatter: (value) => `$${(value / 1000000).toFixed(1)}M` }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Legend, {}), _jsx(Area, { type: "monotone", dataKey: "mrr", stroke: "#10B981", fillOpacity: 1, fill: "url(#colorMrr)", name: "Monthly Revenue", strokeWidth: 2 }), _jsx(Area, { type: "monotone", dataKey: "pipelineValue", stroke: "#3B82F6", fillOpacity: 1, fill: "url(#colorPipeline)", name: "Pipeline Value", strokeWidth: 2 })] }) })] })));
RevenueChart.displayName = 'RevenueChart';
const DeploymentChart = memo(({ data }) => (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl p-6 rounded-xl border border-slate-700/50", children: [_jsxs("h3", { className: "text-lg font-semibold text-white mb-4 flex items-center gap-2", children: [_jsx(Target, { size: 20, className: "text-green-400" }), "Deployment Performance"] }), _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(LineChart, { data: data, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#334155" }), _jsx(XAxis, { dataKey: "month", stroke: "#94a3b8" }), _jsx(YAxis, { yAxisId: "left", stroke: "#94a3b8" }), _jsx(YAxis, { yAxisId: "right", orientation: "right", stroke: "#94a3b8" }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Legend, {}), _jsx(Line, { yAxisId: "left", type: "monotone", dataKey: "timeToDeployDays", stroke: "#EF4444", strokeWidth: 2, dot: { fill: '#EF4444', r: 4 }, name: "Deploy Time (days)" }), _jsx(Line, { yAxisId: "right", type: "monotone", dataKey: "successRate", stroke: "#10B981", strokeWidth: 2, dot: { fill: '#10B981', r: 4 }, name: "Success Rate (%)" })] }) })] })));
DeploymentChart.displayName = 'DeploymentChart';
const PipelineChart = memo(({ data }) => (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl p-6 rounded-xl border border-slate-700/50", children: [_jsxs("h3", { className: "text-lg font-semibold text-white mb-4 flex items-center gap-2", children: [_jsx(Users, { size: 20, className: "text-purple-400" }), "Recruitment Pipeline"] }), _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(BarChart, { data: data, layout: "horizontal", children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#334155" }), _jsx(XAxis, { type: "number", stroke: "#94a3b8" }), _jsx(YAxis, { dataKey: "stage", type: "category", width: 80, stroke: "#94a3b8" }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Bar, { dataKey: "candidates", fill: "#8B5CF6", radius: [0, 8, 8, 0] })] }) })] })));
PipelineChart.displayName = 'PipelineChart';
const ClientDistributionChart = memo(({ data }) => {
    const COLORS = ['#10B981', '#3B82F6', '#8B5CF6', '#F59E0B', '#EF4444'];
    return (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl p-6 rounded-xl border border-slate-700/50", children: [_jsxs("h3", { className: "text-lg font-semibold text-white mb-4 flex items-center gap-2", children: [_jsx(CheckCircle, { size: 20, className: "text-orange-400" }), "Client Distribution by Industry"] }), _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(PieChart, { children: [_jsx(Pie, { data: data, cx: "50%", cy: "50%", innerRadius: 60, outerRadius: 100, fill: "#8884d8", paddingAngle: 2, dataKey: "value", children: data.map((_, index) => (_jsx(Cell, { fill: COLORS[index % COLORS.length] }, `cell-${index}`))) }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Legend, {})] }) })] }));
});
ClientDistributionChart.displayName = 'ClientDistributionChart';
const ChartComponents = ({ data }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsx(RevenueChart, { data: data.revenueData }), _jsx(DeploymentChart, { data: data.deploymentEfficiencyData }), _jsx(PipelineChart, { data: data.pipelineConversionData }), _jsx(ClientDistributionChart, { data: data.clientRetentionData })] }));
};
export default memo(ChartComponents);
//# sourceMappingURL=ChartComponents.js.map